// Base de données locale de la librairie Kitabi avec images locales
const livres = [
  { id: "1",  titre: "Nedjma",               auteur: "Kateb Yacine",          categorie: "Roman",       prix: 1500, note: 4.8, stock: 15, annee: 1956, isbn: "9782070368228", image: "../images/nedjma.jpg", desc: "Chef-d'œuvre explorant l'identité et la quête des origines en Algérie." },
  { id: "2",  titre: "L'Amour, la fantasia", auteur: "Assia Djebar",          categorie: "Histoire",    prix: 1800, note: 4.7, stock: 10, annee: 1955, isbn: "9782290011690", image: "../images/fantasia.jpg", desc: "Récit poétique liant la conquête coloniale aux mémoires des femmes." },
  { id: "3",  titre: "La Grande Maison",     auteur: "Mohammed Dib",          categorie: "Roman",       prix: 1200, note: 4.6, stock: 20, annee: 1952, isbn: "9782070369881", image: "../images/grandemaison.jpg", desc: "La vie difficile du jeune Omar dans un quartier pauvre de Tlemcen." },
  { id: "4",  titre: "Le Fils du pauvre",    auteur: "Mouloud Feraoun",       categorie: "Biographie",  prix: 1100, note: 4.9, stock: 12, annee: 1950, isbn: "9782707301185", image: "../images/filsdupauvre.jpg", desc: "Récit autobiographique touchant sur l'enfance en Kabylie." },
  { id: "5",  titre: "L'Eleve et la lecon",  auteur: "Malek Haddad",          categorie: "Philosophie", prix: 1300, note: 4.5, stock: 8,  annee: 1960, isbn: "",              image: "../images/elevelecon.jpg", desc: "Réflexion sur le déchirement culturel d'un intellectuel algérien." },
  { id: "6",  titre: "Le Vent du Sud",       auteur: "Mohammed Dib",          categorie: "Roman",       prix: 1400, note: 4.4, stock: 14, annee: 1954, isbn: "9782070369904", image: "../images/ventdusud.jpg", desc: "Évoque le combat et la résistance des paysans algériens." },
  { id: "7",  titre: "Novembre",             auteur: "Rachid Boudjedra",      categorie: "Histoire",    prix: 1600, note: 4.6, stock: 9,  annee: 1975, isbn: "9782070408092", image: "../images/novembre.jpg", desc: "Récit marquant le début de la guerre de libération nationale." },
  { id: "8",  titre: "La Répudiation",       auteur: "Rachid Boudjedra",      categorie: "Roman",       prix: 1700, note: 4.3, stock: 11, annee: 1969, isbn: "9782070754571", image: "../images/repudiation.jpg", desc: "Roman brisant les tabous traditionnels d'une écriture puissante." },
  { id: "9",  titre: "Printemps berbere",    auteur: "Tahar Djaout",          categorie: "Poésie",      prix: 900,  note: 4.7, stock: 18, annee: 1978, isbn: "",              image: "../images/printempsberbere.jpg", desc: "Recueil poétique célébrant la beauté des paysages et des racines." },
  { id: "10", titre: "Le Chercheur d'os",    auteur: "Tahar Djaout",          categorie: "Roman",       prix: 1350, note: 4.8, stock: 7,  annee: 1984, isbn: "",              image: "../images/chercheurdos.jpg", desc: "Une quête poignante d'un homme à la recherche des os de son père." },
  { id: "11", titre: "À quoi rêvent les loups", auteur: "Yasmina Khadra",     categorie: "Roman",       prix: 1500, note: 4.6, stock: 22, annee: 1999, isbn: "9782743609580", image: "../images/reve-loups.jpg", desc: "Plongée sombre au cœur de la décennie noire en Algérie." },
  { id: "12", titre: "Morituri",             auteur: "Yasmina Khadra",        categorie: "Roman",       prix: 1250, note: 4.5, stock: 16, annee: 1997, isbn: "9782743606060", image: "../images/morituri.jpg", desc: "Polar policier mené à Alger par le célèbre commissaire Llob." },
  { id: "13", titre: "Histoire de l'Algérie", auteur: "Charles-Robert Ageron", categorie: "Histoire",    prix: 2200, note: 4.9, stock: 5,  annee: 1994, isbn: "9782130445289", image: "../images/histoirealgerie.jpg", desc: "Ouvrage complet sur l'histoire algérienne depuis l'Antiquité." },
  { id: "14", titre: "L'Algérie dans tous ses états", auteur: "Collectif",    categorie: "Histoire",    prix: 1800, note: 4.4, stock: 13, annee: 2012, isbn: "",              image: "../images/algerieetats.jpg", desc: "Panorama social et culturel de la société algérienne moderne." },
  { id: "15", titre: "Biologie cellulaire",  auteur: "Claude Perrot",         categorie: "Science",     prix: 2800, note: 4.6, stock: 20, annee: 2015, isbn: "9782100720071", image: "../images/biologie.jpg", desc: "Livre scientifique de référence sur les mécanismes cellulaires." },
  { id: "16", titre: "Mathématiques appliquées", auteur: "Ahmed Riad",        categorie: "Science",     prix: 2500, note: 4.5, stock: 18, annee: 2018, isbn: "",              image: "../images/maths.jpg", desc: "Livre d'algèbre et probabilités pour étudiants en sciences." },
  { id: "17", titre: "Le Prince",            auteur: "Machiavel",             categorie: "Philosophie", prix: 1100, note: 4.7, stock: 25, annee: 1532, isbn: "9782080700087", image: "../images/leprince.jpg", desc: "Traité d'analyse politique classique sur la gestion du pouvoir." },
  { id: "18", titre: "Tintin au Congo",      auteur: "Hergé",                 categorie: "Jeunesse",    prix: 1900, note: 4.2, stock: 10, annee: 1931, isbn: "9782203001015", image: "../images/tintincongo.jpg", desc: "Bande dessinée narrant les aventures de Tintin et Milou en Afrique." },
  { id: "19", titre: "Fables",               auteur: "Jean de La Fontaine",   categorie: "Poésie",      prix: 800,  note: 4.8, stock: 30, annee: 1668, isbn: "9782011681515", image: "../images/fables.jpg", desc: "Histoires courtes d'animaux pour illustrer des leçons de morale." },
  { id: "20", titre: "Ibn Khaldoun - Les Prolégomènes", auteur: "Ibn Khaldoun", categorie: "Histoire",  prix: 2400, note: 4.9, stock: 8,  annee: 1377, isbn: "",              image: "../images/prolegomenes.jpg", desc: "Œuvre historique majeure fondatrice de la sociologie moderne." }
];
